### ISSUE TITLE
3D Model's colors not rendering.

### ISSUE THREAD

**Issue by Jass2k23** [a-trost/creative-portfolio#6]
![Screenshot 2024-07-05 at 12 14 26 PM](https://github.com/a-trost/creative-portfolio/assets/94312817/f0fe335c-171e-4a3a-9a17-cbe152a11b02)

**Comment by a-trost** [comment]
This is a side effect of #5 , because without the environment or any other lights in the scene, the objects will be completely black. Adding a light should make this scene show the materials.
